##config
---
## 개발
development:
  comm:
    nodePort: 8080
  db:
    database: postgres
    username: docker
    password: docker
    host: localhost
    port: '15432'
    dialect: postgres
    operatorAliases: false
    quoteIdentifiers: false
    timezone: "+09:00"
    logQueryParameters: false
    logging: true

## 운영 (현재 안씀!)
production:
  comm:
    nodePort: 8080
  db:
    database: postgres
    username: docker
    password: docker
    host: localhost
    port: '15432'
    dialect: postgres
    operatorAliases: false
    quoteIdentifiers: false
    timezone: "+09:00"
    logQueryParameters: false
    logging: false